version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: olmosbek
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: todo-app-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: